version: '3.4'

services:
  gitversion:
    build:
      context: .
      args:
        GITVERSION: ${GITVERSION:-v4.0.0-beta.14}
        GITVERSION_NUGET: ${GITVERSION_NUGET:-4.0.0-beta0014}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    volumes:
      - ./:/repo/
